GetTokenAt stops at latest segment
AxonIQ/axon-server-se pull request #182
Opened 2020-10-12 05:46 UTC by MGathier

if the first event in a segment has a timestamp after the requested time return null to continue to the previous segment.

2020-10-23 09:45 UTC, saratry requested changes

2020-10-23 09:45 UTC, saratry commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/EventIterator.java
>              if (event.getEvent().getTimestamp() <= instant) {
if the timestamp is equal to instant, we should return the same token, not the next one. So I think that in this clause we need < i.o. <=

2020-10-26 12:38 UTC, saratry approved these changes

2020-10-26 12:38 UTC, m1l4n54v1c approved these changes

2020-10-26 13:16 UTC, merged