Memory mapped indexes kept open too long
AxonIQ/axon-server-se pull request #184
Opened 2020-10-12 07:52 UTC by MGathier

use file channels to open older index files to have more control on close.

2020-10-23 09:59 UTC, saratry requested changes
The maxMmapIndex field name is not clear to me. See my comment.

2020-10-23 09:59 UTC, saratry requested changes

2020-10-23 09:59 UTC, saratry commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/StandardIndexManager.java
> +    private final AtomicLong maxMmapIndex = new AtomicLong();
the name of this field is not clear to me: I suggest in alternative
- minMmapIndex (the segment should be greater than this index to use Memory Mapped Files)
- useMmapAfterIndex
- maxChannelIndex (the segment shoudl be less than this index to use FileChannel)
- useChannelBeforeIndex

or, if you want to be generic:
- mMapThreshold

updateMaxMmapIndex method name should be consisten with the field name.

2020-10-26 12:46 UTC, saratry approved these changes

2020-10-26 12:46 UTC, m1l4n54v1c approved these changes

2020-10-26 13:15 UTC, merged