Disk usage metrics and health indicators
AxonIQ/axon-server-se pull request #237
Opened 2021-01-28 15:38 UTC by stefanvozd

Added disk usage metrics and health indicators

2021-01-30 10:08 UTC, abuijze requested changes
Minor change in logging requested

2021-02-01 07:22 UTC, MGathier requested changes
For the health indicator I would create a bean AxonServerDiskSpaceHealthIndicator extending 
the spring DiskSpaceHealthIndicator, and have the PrimaryEventStore instances register a location 
with this health indicator bean. This would make the whole implementation of the disk space health check a lot easier, and allow EE to register another FileSystem for the replication log. 

For the metrics I would let the PrimaryEventStore register the DiskSpaceMetrics.

2021-02-01 07:22 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/config/AxonServerDiskMetricsConfig.java
> +    public AxonServerDiskMetricsConfig(LocalEventStore localEventStore) {
Disk space metrics may not be relevant for all types of event stores, The metrics are only relevant for the current implementation of the EventStorageEngine.

2021-02-01 07:22 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/config/DiskSpaceHealthIndicatorConfiguration.java
> +                logger.warn(String.format("Free disk space below threshold. Available: %d bytes (threshold: %s)", diskFreeInBytes, this.threshold));
Add this.path to logging to show for which path the disk space is running out.

2021-02-01 07:22 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/config/DiskSpaceHealthIndicatorConfiguration.java
> +                builder.status(new Status("WARN"));
Move class io.axoniq.axonserver.enterprise.HealthStatus from EE to SE, and use HealthStatus.WARN_STATUS.

2021-02-01 07:22 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventStorageEngine.java
> +    default void health(Health.Builder builder, DiskSpaceHealthIndicatorProperties diskSpaceHealthIndicatorProperties) {
These properties should not be part of the health operation, but set on the EventStorageImplementation level.

2021-02-01 07:22 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/SegmentBasedEventStore.java
>          while (n != null) {
this while loop can be removed, was part of an initial implementation of multi-location storage that is no longer implemented.

2021-02-01 12:46 UTC, stefanvozd commented on axonserver/src/main/java/io/axoniq/axonserver/config/AxonServerDiskMetricsConfig.java
> +                DiskSpaceMetrics diskSpaceMetrics = new DiskSpaceMetrics(fileSystem.getPath("/").toFile(), Tags.of("fileSystem", fileSystem.toString()));
should I add some other tag instead?

2021-02-04 06:55 UTC, MGathier approved these changes

2021-02-04 06:55 UTC, MGathier commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/EventStreamReader.java
> +import org.springframework.boot.actuate.autoconfigure.system.DiskSpaceHealthIndicatorProperties;
unused import

2021-02-04 06:55 UTC, MGathier commented on axonserver/src/test/java/io/axoniq/axonserver/localstorage/FakeEventStore.java
> +import java.nio.file.Path;
unused import

2021-02-04 06:55 UTC, MGathier commented on axonserver/src/test/java/io/axoniq/axonserver/rest/HttpStreamingQueryTest.java
> +import java.nio.file.Path;
unused

2021-02-08 16:18 UTC, merged