Fix list aggregate events performance issues
AxonIQ/axon-server-se pull request #314
Opened 2021-06-17 14:28 UTC by stefanvozd

Fixes issues: 
- parallel segment reading
- initial sequence number always starts from zero
- events prefetching 
- reading events on gRPC threads
- reading snapshots on gRPC threads

2021-06-17 19:46 UTC, abuijze requested changes

2021-06-17 19:46 UTC, abuijze commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/AggregateReader.java
> +            .filter(snapshot -> snapshot.getAggregateSequenceNumber() >= maxSequenceNumber);
I don't understand this one. Should it be >= minSequenceNumber instead?

2021-06-17 19:46 UTC, abuijze commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/DataFeatcherSchedulerProvider.java
> +public class DataFeatcherSchedulerProvider implements Supplier<ExecutorService> {
Typo in class name. 

This class is fine for an urgent bug-fix, but we should really get rid of 'global variables' as soon as we can.

2021-06-17 19:46 UTC, abuijze commented on axonserver/src/main/java/io/axoniq/axonserver/localstorage/LocalEventStore.java
> +    public final ExecutorService dataFetcher;
Let's avoid public fields

2021-06-17 19:46 UTC, abuijze commented on axonserver/src/main/java/io/axoniq/axonserver/message/event/EventDispatcher.java
> +                           @Value("${axoniq.axonserver.event.aggregate.prefetch:5}") int aggregateEventsPrefetch) {
I think we document the default values in the ref guide. If we change it, we should document the new default there

2021-06-23 11:34 UTC, MGathier approved these changes

2021-06-23 12:54 UTC, saratry approved these changes

2021-06-25 07:53 UTC, merged